name: 🐞 Bug report
description: Create a bug report to help us improve AiDotNet
title: "[BUG]: "
labels: [Bug] 
body:
- type: markdown
  attributes:
    value: |
      Thanks for taking the time to fill out this bug report! Please fill out the form in English!
- type: checkboxes
  attributes:
    label: Is there an existing issue for this?
    description: Please search to see if an issue already exists for the bug you encountered.
    options:
    - label: I have searched the existing issues
      required: true
- type: textarea
  attributes:
    label: Current Behavior
    description: A concise description of any exceptions or errors you encountered.
    placeholder: |
      When I do <X>, <Y> happens and I see the error message attached below:
      ```...```
  validations:
    required: false
- type: textarea
  attributes:
    label: Expected Behavior
    description: A concise description of what you expected to happen.
    placeholder: When I do <X>, <Z> should happen instead.
  validations:
    required: false
- type: textarea
  attributes:
    label: Steps To Reproduce
    description: Add steps to reproduce this behavior, including console / network logs & screenshots
    render: markdown
  validations:
    required: false
- type: textarea
  attributes:
    label: Environment
    description: |
      Enter the Environment Details:
    value: |
      - AiDotNet Nuget Version: 
      - OS (version, bitness): 
      - .NET SDK (version):
      - target process .NET version/bitness:
    render: markdown
  validations:
    required: false
- type: textarea
  attributes:
    label: Anything else?
    description: |
      Links? References? Anything that will give us more context about the issue you are encountering!
  validations:
    required: false
